### PR TITLE
abaplint.json, fix version

### LINKED ISSUE #1: abaplint bugs
hi,
fyi, I have opened https://github.com/abaplint/abaplint/issues/1777 to fix the false positives

### PR DESCRIPTION
**Pull request by larshp**
fix version value,

will also close #1 when the commit is merged to master,

image

### CODE REVIEW

**Comment by se38** [comment]
@larshp 
Do you have an idea, why the standard interface is not found?
`Implemented interface "IF_AMDP_MARKER_HDB" not found`

The linter also marked two empty lines. Both are within the AMDP procedure.  Maybe thats the reason? In my opinion they are okay.

```
  METHOD get_nearest
    BY DATABASE PROCEDURE FOR HDB
    LANGUAGE SQLSCRIPT
    OPTIONS READ-ONLY
    USING zchargingpoints.

    e_nearest = SELECT TOP 10
                  geo.ST_AsGeoJSON() as geojson,
                  NEW ST_POINT(i_longitude, i_latitude).ST_SRID(4326).ST_Distance(geo, 'kilometer') AS distance
                  FROM zchargingpoints
                  ORDER BY distance;
---> this one
  ENDMETHOD.
```

**Comment by larshp** [comment]
IF_AMDP_MARKER_HDB added in https://github.com/abaplint/deps/pull/33

abaplint must know the interfaces implemented and superclasses in order to make a somewhat qualified syntax check, the deps are defined in https://github.com/se38/AbapSpatial/blob/main/abaplint.json#L13

**Comment by larshp** [comment]
`empty_line_in_statement` false positives will be fixed by https://github.com/abaplint/abaplint/pull/1778

**Comment by se38** [comment]
Perfect. 
In the meantime I've deleted the two empty lines (although I don't like the formating now). All green now.

Gracias mi amigo.

**Comment by se38** [comment]
Oh, just saw your "empty_line_in_statement" comment ....

**Comment by larshp** [comment]
@se38 try pushing a new commit, the `empty_line_in_statement` false positives should be fixed now

**Comment by se38** [comment]
@larshp Green with empty lines :-)

**Pull request merged**
